/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_total_free(a: number): void;
export function __wbg_get_total_combination(a: number): number;
export function __wbg_set_total_combination(a: number, b: number): void;
export function __wbg_get_total_key_range_group(a: number): number;
export function __wbg_set_total_key_range_group(a: number, b: number): void;
export function total_get_cards(a: number): number;
export function total_show_cards(a: number): number;
export function total_show_combination(a: number, b: number): void;
export function total_get_player_id(a: number, b: number): void;
export function total_get_win_pot(a: number): number;
export function __wbg_card_free(a: number): void;
export function __wbg_get_card_n(a: number): number;
export function __wbg_set_card_n(a: number, b: number): void;
export function __wbg_get_card_m(a: number): number;
export function __wbg_set_card_m(a: number, b: number): void;
export function card_new(a: number, b: number): number;
export function card_get(a: number): number;
export function card_show_card(a: number, b: number): void;
export function __wbg_hand_free(a: number): void;
export function hand_new(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number): number;
export function hand_show_hand(a: number, b: number): void;
export function __wbg_menager_free(a: number): void;
export function menager_new(a: number): number;
export function menager_add_hand(a: number, b: number): void;
export function menager_calculate(a: number): number;
export function __wbg_pot_free(a: number): void;
export function pot_new(a: number): number;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_free(a: number, b: number): void;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number): number;
